version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: job_log
    volumes:
      - ./db-data/:/var/lib/postgresql/data/