# Generated by Django 3.2.14 on 2022-10-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_track_app', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=200),
        ),
    ]
