# Generated by Django 3.2.14 on 2022-10-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_track_app', '0005_activity_gpspoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=80.0),
        ),
    ]
