# Generated by Django 3.2.14 on 2022-12-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_track_app', '0006_auto_20221028_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='total_mass',
            field=models.FloatField(default=95),
            preserve_default=False,
        ),
    ]
